build: false
shallow_clone: true

environment:

  global:
    distutils_use_sdk: 1
    ets_toolkit: "qt4"

  matrix:

    - python: "C:/Python27-x64"
      sdkver: "v7.0"

    - python: "C:/Python34-x64"
      sdkver: "v7.1"

cache:
  - c:\temp

init:
  - ps: $Env:sdkbin = "C:\Program Files\Microsoft SDKs\Windows\" + $Env:sdkver + "\Bin"
  - ps: $Env:sdkverpath = "C:/Program Files/Microsoft SDKs/Windows/" + $Env:sdkver + "/Setup/WindowsSdkVer.exe"
  - ps: $Env:path = $Env:python + ";" + $Env:python + "\scripts;" + $Env:sdkbin + ";" + $Env:path

install:
  - ps: if ((Test-Path "c:/temp") -eq 0) { mkdir c:/temp }
  - ps: python -m pip install --upgrade --no-binary wheel pip
  - ps: pip install --upgrade wheel
  - ps: pip --version
  - cmd /v:on /e:on /c ".\appveyor-install.cmd"
test_script:
  - cmd /v:on /e:on /c ".\appveyor-test.cmd"
